INSERT INTO "public"."categories" 
    ("name", "slug") 
VALUES ('Electronics', 'electronics'), 
    ('Fashion', 'fashion'), 
    ('Real Estates', 'real-estates'), 
    ('Health & Beauty', 'health-beauty'), 
    ('Phones & Tablets', 'phones-tablets'), 
    ('Computers', 'computers'), 
    ('Furniture', 'furniture'), 
    ('Vehicles & Tracks', 'vehicles-tracks'), 
    ('Other', 'other'), 
    ('Food & Restaurants', 'food-restaurants'), 
    ('Motorbikes', 'motorbikes-tricycles'), 
    ('Household Supplies', 'home-supplies-cookware'), 
    ('Jewellery', 'jewellery'), 
    ('Art & Craft', 'art-craft'), 
    ('Hobbies', 'hobbies'), 
    ('Sports & Fitness', 'sports-fitness'), 
    ('Jobs', 'jobs'), 
    ('Services', 'services'), 
    ('Babies', 'babies'), 
    ('Pets', 'pets'), 
    ('Agriculture', 'agriculture'), 
    ('Industry & Machinery', 'industry-machinery');



INSERT INTO "public"."sub_categories" 
    ("name", "category_id", "slug", "default_specs") 
VALUES 
    ('Home & Kitchen Appliances', 'electronics', 'home-kitchen-appliances', 'condition, voltage rating, power in watts,  color, capacity'), ('Tvs', 'electronics', 'tvs', 'condition, voltage rating, power in watts,  color, size, scratches'), 
    ('Fridges', 'electronics', 'fridges', 'condition, voltage rating, power in watts,  color, capacity, scratches'), 
    ('Parts & Accessories', 'electronics', 'parts-accessories-electronics', 'condition, voltage rating, power in watts,  color'), 
    ('Wiring & Electrical Installation', 'electronics', 'wiring-electrical-installation', 'condition, voltage rating, power in watts,  color'), 
    ('Children & Babies', 'fashion', 'children-babies', 'condition, size, color, Machine wash'), 
    ('Women', 'fashion', 'females', 'condition, size, color, Machine wash'), 
    ('Houses & Appartments for Sale', 'real-estates', 'houses-appartments-for-sale', 'condition, Area, selfcontained, toilets, bathrooms, bedrooms, kitchen, compound, floors, Land name'), 
    ('Laptops', 'computers', 'laptops', 'condition, make, color, ram, rom, procesor, speed, screen size, usb ports, battery capacity, external Battery, scratches'), 
    ('Cars', 'vehicles-tracks', 'cars', 'condition, color, year of make, engine size, horse power, torque, fuel, fuel tank capacity, scratches, faults, steering, transmision, passengers, boot size, wheel size'), 
    ('Buses', 'vehicles-tracks', 'buses', 'condition, color, year of make, engine size, horse power, torque, fuel, fuel tank capacity, scratches, faults, steering, transmision, passengers, boot size, wheel size'), 
    ('Tracks & Trailers', 'vehicles-tracks', 'tracks-trailers', 'condition, color, year of make, engine size, horse power, torque, fuel, fuel tank capacity, scratches, faults, steering, transmision, wheel size, trailers, passengers'), 
    ('Pickups', 'vehicles-tracks', 'pickups', 'condition, color, year of make, engine size, horse power, torque, fuel, fuel tank capacity, scratches, faults, steering, transmision, passengers, boot size, wheel size, load capacity, carbin'), 
    ('Parts & Accessories', 'vehicles-tracks', 'parts-accessores-vehicles', 'condition, color, year of make, engine size, horse power, torque, fuel, fuel tank capacity, scratches, faults, steering, transmision'), 
    ('Men', 'fashion', 'males', 'condition, size, color, Machine wash'), 
    ('Shoes', 'fashion', 'shoes', 'condition, size, color, Machine wash'), 
    ('Cosmetics', 'health-beauty', 'cosmetics', 'age, gender, skin type'), 
    ('Jewelry & Wearables', 'fashion', 'jewelry-wearables', 'condition, size, color, make, material'), 
    ('Skincare & Makeup', 'health-beauty', 'skincare-makeup', 'age, gender, skin type'), 
    ('Perfumes & Deodrants', 'health-beauty', 'perfumes-deodrants', 'age, gender, skin type'), 
    ('Gym', 'health-beauty', 'gym', 'age, gender'), 
    ('House Furniture', 'furniture', 'house-furniture', 'condition, wood type, color, size, damages'), 
    ('Office Furniture', 'furniture', 'office-furniture', 'condition, wood type, color, size, damages'), 
    ('Kitchen Furniture', 'furniture', 'kitchen-furniture', 'condition, wood type, color, size, damages'), 
    ('Land & Plots for Sale', 'real-estates', 'land-plots-for-sale', 'condition, Area, Land name, Land Texture'), 
    ('Accessories', 'phones-tablets', 'phone-tablet-accessories', 'condition, screen size, ram, rom, color, scratches'), 
    ('Cell Phones', 'phones-tablets', 'cell-phones', 'condition, screen size, ram, rom, color, scratches, sim card slot, card size, battery capacity, battery size, battery type'),
    ('Space for Rent', 'real-estates', 'space-for-rent', 'condition, Area'), 
    ('Desktops', 'computers', 'desktops', 'condition, make, color, ram, rom, procesor, speed, screen size, usb ports, scratches'), 
    ('Accessories', 'computers', 'computor-accessories', 'condition, make, color'), 
    ('Houses & Appartments for Rent', 'real-estates', 'house-appartments-for-rent', 'condition, Area, selfcontained, toilets, bathrooms, bedrooms, kitchen, compound, floors'), 
    ('Tablets', 'phones-tablets', 'tablets', 'condition, screen size, ram, rom, color, scratches, sim card slot, card size, battery capacity, battery size, battery type'), 
    ('Kids & Playgrounds', 'furniture', 'kids-playground', 'condition, wood type, color, size, damages'), 
    ('Tractors & Heavy Equipments', 'vehicles-tracks', 'tractors-heavy-equipments', 'condition, color, year of make, engine size, horse power, torque, fuel, fuel tank capacity, scratches, faults, steering, transmision, wheel size, load capacity'), 
    ('Sports Wear', 'fashion', 'sports_wear', ''), 
    ('Food', 'food-restaurants', 'food', ''), 
    ('Restaurants', 'food-restaurants', 'restaurants', ''), 
    ('Motorbikes', 'motorbikes-tricycles', 'motorbikes', ''), 
    ('Tricycles', 'motorbikes-tricycles', 'tricycles', ''), 
    ('Scooters', 'motorbikes-tricycles', 'scooters', ''), 
    ('Commercial Property', 'real-estates', 'commercial-property', 'type,dimensions,condition'), 
    ('Venues', 'real-estates', 'venues', ''), 
    ('Smart Watches & Trackers', 'phones-tablets', 'smart-watches-trackers', 'os,ram,rom,color,brand,material'), 
    ('Cameras', 'electronics', 'cameras', 'SD-Card,Size,Color,brand,zooming'), 
    ('Music & Audio', 'electronics', 'music-audio', ''), 
    ('Networking Equipments', 'electronics', 'networking-quipments', ''), 
    ('Security & Surveillance', 'electronics', 'security-surveillance', ''), 
    ('Home Appliances', 'electronics', 'home-appliances', ''), 
    ('Video Gaming', 'electronics', 'video-gaming', ''), 
    ('Repairs & Maintainance', 'electronics', 'electronics-repairs-maitainance', ''), 
    ('Monitors', 'computers', 'monitors', ''), 
    ('Printers', 'computers', 'printers', ''), 
    ('Software', 'computers', 'software', ''), 
    ('Hardware', 'computers', 'hardware', ''), 
    ('Construction & Shattering', 'furniture', 'construction-shattering', ''), 
    ('Compound Furniture', 'furniture', 'compound-furniture', ''), 
    ('Soaps & Detergents', 'home-supplies-cookware', 'soaps-detergents', ''), 
    ('Beddings', 'home-supplies-cookware', 'beddings', ''), 
    ('Carpets', 'home-supplies-cookware', 'carpets', ''), 
    ('Kitchen Utensils', 'home-supplies-cookware', 'kitchen-utensils', ''), 
    ('Plastics', 'home-supplies-cookware', 'plastics', ''), 
    ('Others', 'home-supplies-cookware', 'others', ''), 
    ('Bath & Body', 'health-beauty', 'bath-body', ''), 
    ('Hair & Facial', 'health-beauty', 'hair-facial', ''), 
    ('Tools & Accessories', 'health-beauty', 'tools-accessories', ''), 
    ('Vitamins & Supplements', 'health-beauty', 'vitamins-supplements', ''), 
    ( 'Sexual Wellness', 'health-beauty', 'sexual-wellness', ''), 
    ('Bags', 'fashion', 'bags', ''), 
    ('Wedding & Party Accessories', 'fashion', 'wedding-party-accessories', ''), 
    ('Watches', 'jewellery', 'watches', ''), 
    ('A Parure', 'jewellery', 'parure', ''), 
    ('Necklaces', 'jewellery', 'necklaces', ''), 
    ('Rings & Bridal', 'jewellery', 'rings-bridal', ''), 
    ('Earrings', 'jewellery', 'earrings', ''), 
    ('Bracelets', 'jewellery', 'bracelets', ''), 
    ('Bangles', 'jewellery', 'bangles', ''), 
    ('Brooch', 'jewellery', 'brooch', ''), 
    ('Other', 'jewellery', 'other-jewellery', ''), 
    ('Textile', 'art-craft', 'textile', ''), 
    ('Wood', 'art-craft', 'wood', ''), 
    ('Flower', 'art-craft', 'flower', ''), 
    ('Metal Works', 'art-craft', 'metal-works', ''), 
    ('Leather Work', 'art-craft', 'leather-work', ''), 
    ('Fashion Craft', 'art-craft', 'fashion-craft', ''), 
    ('Niddle Work', 'art-craft', 'niddle-work', ''), 
    ('Mixed Media', 'art-craft', 'mixed-media', ''), 
    ('Paper Craft', 'art-craft', 'paper-craft', ''), 
    ('Pottery & Clay', 'art-craft', 'pottery-clay', ''), 
    ('Painting', 'art-craft', 'painting', ''), 
    ('Books & Novels', 'hobbies', 'books-novels', ''), 
    ('Photography', 'hobbies', 'photography', ''), 
    ('Camping', 'hobbies', 'camping', ''), 
    ('Other Hobbies', 'hobbies', 'other-hobbies', ''), 
    ('Tools & Accessories', 'hobbies', 'hoobies-tools-accessories', ''), 
    ('Sports Equipents', 'sports-fitness', 'sports-equipments', ''), 
    ('Sports Ware', 'sports-fitness', 'sports-ware', ''), 
    ('Gym', 'sports-fitness', 'sports-gym', ''), 
    ('Gym Equipments', 'sports-fitness', 'gym-equipments', ''), 
    ('Find A Job', 'jobs', 'find-job', ''), 
    ('Hiring', 'jobs', 'hiring', '');
