import { Category, Listing, Message, Store } from "../types";

export const ads: Listing[] = [
  {
    id: "1",
    title:
      "Hisense 32 Inch Flat TV With Free To Air Decoder Full HD LED TV - Black",
    price: 50,
    originalPrice: 100,
    currency: "USD",
    pricingScheme: "fixed",
    image: "https://placehold.co/400x400",
    store_id: "1",
    store: {
      id: "1",
      name: "Store 1",
    },
    rating: 4.89,
    ratings: 48,
  },
  {
    id: "2",
    title: `Samsung Galaxy A16 4G 6.7" 4GB RAM 128GB ROM 50MP 5000mAh - Blue Black`,
    price: 500,
    pricingScheme: "fixed",
    currency: "USD",
    image: "https://placehold.co/600x400",
    store_id: "1",
    store: {
      id: "1",
      name: "Store 1",
    },
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "3",
    title: `Nokia 3210 - 2.4" 64MB RAM 128MB ROM 2MP 1450mAh - Black`,
    price: 20,
    originalPrice: 50,
    pricingScheme: "fixed",
    currency: "USD",
    image: "https://placehold.co/600x400",
    store_id: "1",
    store: {
      id: "1",
      name: "Store 1",
    },
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "4",
    title: "NIVEA Essentials Rich Caring Body Cream 400ml",
    minPrice: 200,
    maxPrice: 500,
    pricingScheme: "range",
    currency: "USD",
    image: "https://placehold.co/600x400",
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "5",
    title: "Apple Iphone 12 Pro 128GB - Pacific Blue",
    price: 100,
    period: "month",
    pricingScheme: "recurring",
    currency: "USD",
    image: "https://placehold.co/600x400",
    store_id: "1",
    store: {
      id: "1",
      name: "Store 1",
    },
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "6",
    title: `Apple IPhone 11 6.1" Single SIM 4GB RAM 64GB ROM 12MP - Black`,
    price: 20,
    originalPrice: 50,
    pricingScheme: "recurring",
    period: "week",
    currency: "USD",
    image: "https://placehold.co/600x400",
    rating: 2.3,
    ratings: 89,
    store_id: "1",
    store: {
      id: "1",
      name: "Store 1",
    },
  },
  {
    id: "7",
    title: "Laptop",
    minPrice: 500,
    originalPrice: 600,
    pricingScheme: "range",
    currency: "USD",
    image: "https://placehold.co/600x400",
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "8",
    title: "Chair",
    pricingScheme: "range",
    minPrice: 20,
    currency: "USD",
    image: "https://placehold.co/600x400",
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "9",
    title: "Phone",
    price: 200,
    pricingScheme: "fixed",
    currency: "USD",
    image: "https://placehold.co/600x400",
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "10",
    title: "Table",
    price: 2,
    units: "Kg",
    pricingScheme: "unit",
    currency: "USD",
    image: "https://placehold.co/600x400",
    rating: 2.3,
    ratings: 89,
    store_id: "1",
    store: {
      id: "1",
      name: "Store 1",
    },
  },
  {
    id: "11",
    title: "Bicycle",
    price: 2,
    units: "Kg",
    originalPrice: 3,
    pricingScheme: "unit",
    currency: "USD",
    image: "https://placehold.co/400x400",
    store_id: "1",
    store: {
      id: "1",
      name: "Store 1",
    },
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "12",
    title: "Laptop",
    price: 500,
    period: "month",
    pricingScheme: "recurring",
    currency: "USD",
    image: "https://placehold.co/600x400",
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "13",
    title: "Chair",
    price: 20,
    originalPrice: 25,
    period: "week",
    pricingScheme: "recurring",
    currency: "USD",
    image: "https://placehold.co/600x400",
    store_id: "1",
    store: {
      id: "1",
      name: "Store 1",
    },
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "14",
    title: "Phone",
    pricingScheme: "fixed",
    price: 200,
    currency: "USD",
    image: "https://placehold.co/600x400",
    rating: 2.3,
    ratings: 89,
  },
  {
    id: "15",
    title: "Table",

    priceMenu: [
      {
        price: "20",
        image: "https://placehold.co/400x400",
        title: "Menu item 1",
        description: "Menu item description",
      },
      {
        price: "20",
        image: "https://placehold.co/400x400",
        title: "Menu item 2",
        description: "Menu item description",
      },
      {
        price: "20",
        image: "https://placehold.co/400x400",
        title: "Menu item 3",
        description: "Menu item description",
      },
      {
        price: "20",
        image: "https://placehold.co/400x400",
        title: "Menu item 4",
        description: "Menu item description",
      },
    ],
    pricingScheme: "menu",
    currency: "USD",
    image: "https://placehold.co/600x400",
    rating: 2.3,
    ratings: 89,
  },
];

export const stores: Store[] = [
  {
    id: "1",
    name: "Best electronics Store 1",
    description:
      "A really really long description of the store describing its products and services.",
    logo: "",
  },
  {
    id: "2",
    name: "A realy realy long store name like, Store 1",
    logo: "",
  },
  {
    id: "3",
    name: "Store 1",
    logo: "",
  },
  {
    id: "4",
    name: "Store 1",
    logo: "",
  },
  {
    id: "5",
    name: "Store 1",
    logo: "",
  },
  {
    id: "6",
    name: "Store 1",
    logo: "",
  },
  {
    id: "7",
    name: "Store 1",
    logo: "",
  },
];

export const categories: Category[] = [
  {
    name: "Electronics",
    slug: "electronics",
    adsCount: 1245,
    subCategories: [
      {
        id: "1",
        name: "Tvs",
        slug: "tvs",
        category_id: "1",
        adsCount: 123,
      },
      {
        id: "2",
        name: "Home Appliances",
        slug: "home_appliances",
        category_id: "1",
        adsCount: 382,
      },
      {
        id: "3",
        name: "Fridges",
        slug: "fridges",
        category_id: "1",
        adsCount: 403,
      },
      {
        id: "4",
        name: "Wiring & Installation",
        slug: "wiring_and_installation",
        category_id: "1",
        adsCount: 337,
      },
    ],
    id: "1",
  },
  {
    name: "Clothing",
    slug: "clothing",
    adsCount: 876,
    subCategories: [
      {
        id: "5",
        name: "Men's clothing",
        slug: "mens_clothing",
        category_id: "2",
      },
      {
        id: "6",
        name: "Children's clothing",
        slug: "childrens_clothing",
        category_id: "2",
      },
      {
        id: "7",
        name: "Women's clothing",
        slug: "womens_clothing",
        category_id: "2",
      },
      {
        id: "8",
        name: "Casual & Sports clothing",
        slug: "casual_and_sports_clothing",
        category_id: "2",
      },
    ],
    id: "2",
  },
  {
    name: "Home & Garden",
    adsCount: 543,
    slug: "home_and_garden",
    subCategories: [],
    id: "3",
  },
  {
    name: "Sports & Outdoors",
    slug: "sports_and_outdoor",
    adsCount: 321,
    subCategories: [],
    id: "4",
  },
  {
    name: "Beauty & Health",
    slug: "beauty_and_health",
    adsCount: 654,
    subCategories: [],
    id: "5",
  },
  {
    name: "Toys & Games",
    slug: "toys_and_games",
    adsCount: 432,
    subCategories: [],
    id: "6",
  },
  {
    name: "Automotive",
    slug: "automotive",
    adsCount: 234,
    subCategories: [],
    id: "7",
  },
  {
    name: "Books & Media",
    slug: "books_and_media",
    adsCount: 543,
    subCategories: [],
    id: "8",
  },
];

export const messages: Message[] = [
  {
    id: "1",
    sender: "1",
    receiver: "2",
    text: "Hello",
  },
  {
    id: "2",
    sender: "2",
    receiver: "1",
    text: "Hello, how are you?",
  },
  {
    id: "3",
    sender: "2",
    receiver: "1",
    text: "How may I help you today?",
  },
  {
    id: "4",
    sender: "1",
    receiver: "2",
    text: "I'm doing really well, how about you.?",
  },
  {
    id: "5",
    sender: "1",
    receiver: "2",
    text: "The reason I contacted you today was to find out whether the item is still available.",
  },
  {
    id: "3",
    sender: "2",
    receiver: "1",
    text: "Oh sure, it's still available. Can I send you an invoice?",
  },
];
